### ISSUE TITLE
error process sentinel

### ISSUE THREAD

**Issue by ngnguyen1** [woochica/wakatime-mode#13]
I have installed this plugin. 
Here is my config: 
(setq wakatime-api-key "my-api-key")
(setq wakatime-cli-path "/path-to-wakatime-cli")
(global-wakatime-mode)

But, when i have any change in my files, i get an error in output:
error process sentinel: Unexpected Wakatime error occurred (code 103)
Pls help me
Thx,

**Comment by alanhamlett** [comment]
What version of wakatime-cli do you have?

**Comment by ngnguyen1** [comment]
Hi @alanhamlett ,
I installed wakatime using pip and with sudo command. And version of my wakatime-cli  is 2.1.9.
Thx,

**Comment by alanhamlett** [comment]
Error code 103 means wakatime-cli couldn't read from the config file at `~/.wakatime.cfg`. Does that file exist?

**Comment by ngnguyen1** [comment]
Yup. Thx @alanhamlett . I have solved this problem. Reason for this is i have write config api-key to ~/.wakatime.cfg. 
I think you should improve documentation for emacs editor. When the first time i using waka, i don't understand how to config api-key and wakatime path. But in sublime text and other editors, i very easy to config it. 

Thx,

**Comment by alanhamlett** [comment]
Yep, I need to improve the documentation for wakatime-mode or make it more automatic when first installing.
