### ISSUE TITLE
handle service errors

### ISSUE THREAD

**Issue by woochica** [woochica/wakatime-mode#5]
executing CLI script fails silently without knowing what's happening

**Comment by alanhamlett** [comment]
Can it check the return value from the cli script? Anything other than zero is an error.

**Comment by woochica** [comment]
Exactly, so the CLI script does not fail silenty, it's wakatime-mode that eats its output without handling it properly first.

**Comment by woochica** [comment]
Fixed in e735573c4a50389a67c51d219812edcb4189b67b
